version: '3.8'
services:
  db-mysql:
    image: mysql:latest
    container_name: db-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: examen_parcial
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306" # Cambia el puerto a 3307
    volumes:
      - db_data:/var/lib/mysql
volumes:
  db_data:

